name: Build and Release Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Substitua pela versão específica do Python que você está usando

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify PyInstaller Installation
        run: |
          python -m PyInstaller --version

      - name: Build Executable with PyInstaller
        run: |
          python -m PyInstaller --onefile script.py

      - name: Check if Executable Exists
        run: |
          if not exist dist\script.exe (
            echo "Executable not found!"
            exit 1
          )

      - name: Upload Executable as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: executable
          path: dist/script.exe

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
          draft: false
          prerelease: false
          files: dist/script.exe
