name: Build and Release Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify PyInstaller Installation
        run: |
          python -m PyInstaller --version

      - name: Build Executable with PyInstaller
        run: |
          python -m PyInstaller --onefile script.py

      - name: List dist Directory After Build
        run: |
          dir dist
        shell: cmd

      - name: Check if Executable Exists
        shell: pwsh
        run: |
          if (-not (Test-Path "dist\script.exe")) {
            Write-Output "Executable not found!"
            exit 1
          } else {
            Write-Output "Executable successfully created."
          }

      # 8. Criar Release e Anexar Executável
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: v1.0.${{ github.run_number }}
          name: Release v1.
